# Backtest Configuration File

# Macro News Aggregation Parameters
macro_news_aggregation:
  max_retries: 3                   # Maximum number of retries for the FilterAgent
  chunk_size: 15                   # Discretize news chunks within the date range
  verbose: true                    # Whether to print out the relevant news in news aggregation
  filter_agent: true               # Whether to use LLM for news filtering (or import from CSV)
  prompt_num_relevance: "1-2"      # Number of relevant news to select in each chunk

# Backtesting Configuration Parameters
backtest:
  asset: "US 10-year Treasury bonds"  # Asset for backtesting
  model: "deepseek-r1:8b"             # Model to be used in the backtest
  has_system_prompt: false            # Whether the LLM model includes a system message
  ticker: "IEF"                       # Ticker symbol of the asset

# File Paths and Data Management
file_paths:
  data_root: "DataPipeline/Data"                              # Root directory for data
  output_path: "Backtest/AggregatedData/AggregatedNews.csv"   # Path for aggregated output
  news_path: "ProcessedData/MacroNews.csv"                    # Path for macro news data
  mapping_csv: "MacroIndicators/indicator_mapping.csv"        # Path for the indicator mapping CSV
  macro_csv:
    - "ProcessedData/MacroIndicatorDaily.csv"
    - "ProcessedData/MacroIndicatorWeekly.csv"
    - "ProcessedData/MacroIndicatorMonthly.csv"
    - "ProcessedData/MacroIndicatorQuarterly.csv"

# Backtest Date Configuration
dates:
  - "2022-04-02"  # Start Date
  - "2022-04-03"  # End Date

# Formatting Macro Indicator Prompt
last_periods:
  daily: 10    # Number of periods for daily data
  weekly: 4    # Number of periods for weekly data
  monthly: 6   # Number of periods for monthly data
  quarterly: 4 # Number of periods for quarterly data
