# YAML 1.2
# Debate Driven Strategy
# Backtest Configuration File

# Macro News Aggregation Parameters
macro_news_aggregation:
  max_retries:                                  3                   # Maximum number of retries for the FilterAgent
  chunk_size:                                   20                  # Discretize news chunks within the date range
  verbose:                                      False               # Whether to print out the relevant news in news aggregation
  filter_agent:                                 False               # Whether to use LLM for news filtering (True if no aggregated news available)
  prompt_num_relevance:                         "1-2"                # Number of relevant news to select in each chunk

# Backtesting Configuration Parameters
backtest:
  asset:                                        "US 10-year Treasury bonds"    # Asset for backtesting
  ticker:                                       "IEF"                          # Ticker symbol of the asset
  num_processes:                                1                              # Number of parallel processes to backtest (Parallel processing would lead to ugly logging)
  lookback_period:                              3                              # Number of lookback days for macro news                                  
  max_rounds:                                   5                              # Number of rounds of discussion

  model_aggregate:                              "deepseek-chat"                # LLM Model to be used in the backtest
  aggregate_system_prompt:                      False                          # Whether the Aggregate LLM model includes a system message
  
  multi_agent:                                  True                           # Multi Agent Approach
  # model_trading:                                                               # LLM model to be used for trading decision              
  #   - "deepseek-chat"
  #   - "deepseek-chat"  
  #   - "deepseek-chat"                        
  # trading_system_prompt:                                                       # Whether the Aggregate LLM model includes a system message
  #   - False
  #   - False
  #   - False

  model_trading:                                                               # LLM model to be used for trading decision              
    - "deepseek-reasoner"
    - "deepseek-reasoner"
    - "deepseek-reasoner"                                                
  trading_system_prompt:                                                       # Whether the Aggregate LLM model includes a system message
    - True
    - True
    - True

# File Paths and Data Management
file_paths:
  data_root:                                    "DataPipeline/Data"                                 # Root directory for data
  output_path:                                  "Backtest/AggregatedData/AggregatedNews.csv"        # Path for aggregated output
  news_path:                                    "ProcessedData/MacroNews.csv"                       # Path for macro news data
  mapping_csv:                                  "MacroIndicators/indicator_mapping.csv"             # Path for the indicator mapping csv
  macro_csv:
    - "ProcessedData/MacroIndicatorDaily.csv"
    - "ProcessedData/MacroIndicatorWeekly.csv"
    - "ProcessedData/MacroIndicatorMonthly.csv"
    - "ProcessedData/MacroIndicatorQuarterly.csv"

  results_path:                                 "Results/multi_agent_backtest_results.csv"                      # Path for backtest results csv 

# Backtest Date Configuration
dates:
  - "2023-08-02"  # Start Date
  - "2023-08-02"  # End Date

# Formatting Macro Indicator Prompt
last_periods_list:
  - 10    # Number of periods for daily data
  - 4     # Number of periods for weekly data
  - 6     # Number of periods for monthly data
  - 4     # Number of periods for quarterly data

